# Generated by Django 4.2.4 on 2023-08-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userimage",
            name="image",
        ),
        migrations.AddField(
            model_name="userimage",
            name="first_image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="user_images/"
            ),
        ),
        migrations.AddField(
            model_name="userimage",
            name="second_image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="user_images/"
            ),
        ),
    ]
