# Generated by Django 4.2.4 on 2023-09-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0002_remove_userimage_image_userimage_first_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userimage",
            name="dst_face_index",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userimage",
            name="src_face_index",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
