# Generated by Django 4.2.4 on 2023-09-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0003_userimage_dst_face_index_userimage_src_face_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="userimage",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
