# Generated by Django 4.2.4 on 2023-09-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0004_userimage_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userimage",
            name="status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
