# Generated by Django 4.2.4 on 2023-09-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0005_userimage_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="images/"
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("index", models.IntegerField()),
            ],
        ),
    ]
