# Generated by Django 4.2.4 on 2023-09-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0007_image_initdata_tag_delete_imageindex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="index",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
