# Generated by Django 4.2.4 on 2023-09-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0009_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="isCheck",
            new_name="is_check",
        ),
        migrations.AddField(
            model_name="user",
            name="last_check_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
